rbuchberger/jekyll_picture_tag

- picture_tag.rb
- readme.md
By not opening the image before it is known if the image needs to be resized, it cuts off a great deal of time from a build with all of the images already generated. In my case, it cuts down the build time from 15 seconds to 3 seconds.
> Greatly speed up jekyll builds with no images to generate

- lib/jekyll-picture-tag.rb
Show a console warning when a source image cannot be found and carry on
processing rather than stopping
> Handle missing files

- jekyll-picture-tag.gemspec
Seems to work fine with Jekyll 3 so far. This PR simply bumps the dependency version in the gemspec
> Bump Jekyll dependency

- picture_tag.rb
Respect the HTML spec:
> The src attribute must be present, and must contain a valid non-empty URL potentially surrounded by spaces […]
> If the srcset attribute is present, the sizes attribute may also be present.
(Source: [WhatWG](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element))
Improve degradability: even without a polyfill, or with failing JS, older browsers will still display the default image.
> Switch default `img` attribute from `srcset` to `src`

- jekyll-picture-tag.gemspec
- lib/jekyll-picture-tag/version.rb
Fix #93 
Also reduced specificity of various dependency versions to major versions only. There's still some work to be done here, but I'll push this update now to un-break the installation process.
> Hotfix for Ruby version checking

- lib/jekyll-picture-tag/defaults/global.yml
- lib/jekyll-picture-tag/instructions/configuration.rb
- readme.md
Currently picture-tag is generating absolute URLs for image locations. This causes problems with some plugins, like amp-jekyll, which only work with relative URLs. Also, there really isn't any need for absolute URLs within a website.
Finally, absolute URLs can cause issues with CSP if domains are aliased. An absolute URL from the main site could be blocked by CSP from an aliased site.
The config option `relative_url` is added and the behavior is to only generate relative URLs when set to true. The current absolute URL behavior is the default.
> Add config parameter to output relative url_prefix instead of absolute.

- examples/_data/picture.yml
- lib/jekyll-picture-tag/defaults/presets.yml
- lib/jekyll-picture-tag/output_formats/basics.rb
- lib/jekyll-picture-tag/output_formats/data_attributes.rb
- readme.md
Adds option to include a `<noscript>` tag after `data_*` output formats, so disabling javascript doesn't break all your images.
#104 is relevant here as well, though not as severe. It adds a `<p>` tag between the `<img>` and `<noscript>` tags.
Close #102
> Noscript fallback

- jekyll-picture-tag.gemspec
- lib/jekyll-picture-tag/defaults/global.yml
- lib/jekyll-picture-tag/instructions.rb
- lib/jekyll-picture-tag/instructions/configuration.rb
- lib/jekyll-picture-tag/output_formats/basics.rb
- lib/jekyll-picture-tag/output_formats/data_attributes.rb
- lib/jekyll-picture-tag/output_formats/img.rb
- lib/jekyll-picture-tag/output_formats/picture.rb
- lib/jekyll-picture-tag/utils.rb
- readme.md
Fix #104 
Add `{::nomarkdown}` block to j-p-t's output, along with accompanying logic, default settings, and documentation. 
Update to a new version of objective elements, because it makes handling sibling elements a bit easier.
> Nomarkdown option

- lib/jekyll-picture-tag/utils.rb
Jekyll provides a different context object depending on where it's called from. When called from a normal page, it has a `name` property. When called from a post, it doesn't have a `name`, but it has an `ext`. We have to use the one that exists.
Fix #108
> fix exception when called from posts

- lib/jekyll-picture-tag/utils.rb
I was playing with a [generator](https://jekyllrb.com/docs/plugins/generators/)
and found that `page['name']` is handled a bit differently when they're called. In the
example (and others I've seen) `@name` is set to the output file name. Usually `index.html`.
However, the input file is not a `.html` file. I noticed that `page['ext']` still shows the correct
file type for the input even with `@name` being explicitly set.
The current logic of checking `page['name']` then falling back to `page['ext']`
is causing j-p-t to mis-detect markdown files when going through a generator.
I changed this to try `page['ext']` first and then fallback to `page['name']`.
What I've found is:
1. A page has `page['name']` and no `page['ext']`
2. A post has `page['ext']` and no `page['name']`
3. A post going …
> Change logic for detecting page/post file type

- lib/jekyll-picture-tag/srcsets/basics.rb
fix #115 
The issue was that when I checked the set of widths to generate, I was inadvertently operating on the original set rather than making a copy. Apparently this persists between picture tag instances, I had assumed it would not.
> duplicate targets in widths check

- .gitignore
- jekyll-picture-tag.gemspec
- lib/jekyll-picture-tag/version.rb
I've updated the gem version to 1.3.0 and updated the Jekyll dependency to allow the use of Jekyll version <5. I've tested locally and works as expected. We should add some tests to check these changes don't affect anything obscure; but my knowledge of Ruby/gems is limited sadly :/
https://github.com/robwierzbowski/jekyll-picture-tag/issues/131
> Updated gem to allow the use of Jekyll 4

- lib/jekyll-picture-tag/instructions/html_attributes.rb
Attribute processing was inserting new attributes into jekyll's
attributes hash, persisting them between tags. This change 
duplicates the hash and modifies that copy, rather than the 
original.
fix #123
> Fix attribute persistence

- lib/jekyll_picture_tag/instructions.rb
- lib/jekyll_picture_tag/instructions/preset.rb
- lib/jekyll_picture_tag/output_formats/basics.rb
- lib/jekyll_picture_tag/version.rb
- readme.md
close #124 
Sadly, I haven't found a way to reliably detect when `{::nomarkdown}` tags are necessary. These changes take steps to reduce the frequency, and add a configuration setting to allow the user to override undesired behavior. 
I've written a [wiki page](https://github.com/rbuchberger/jekyll_picture_tag/wiki/Extra-%7B::nomarkdown%7D-tags-or-mangled-html%3F) detailing the issue.
> Nomarkdown mitigation

- lib/jekyll_picture_tag/instructions/preset.rb
Display the jekyll data_dir setting, rather than hardcoding it to
the default.
> Improve "preset not found" warning

- lib/jekyll_picture_tag/defaults/global.yml
- lib/jekyll_picture_tag/generated_image.rb
- lib/jekyll_picture_tag/instructions/configuration.rb
- lib/jekyll_picture_tag/source_image.rb
close #37
This pull request adds a new global setting: `ignore_missing_images:`. It does what it says-- allows the site build to continue even if all your images aren't there. 
This setting can accept a boolean value, a jekyll environment name, or an array of jekyll environment names.
> Continue on missing

- docs/output.md
- docs/presets.md
- docs/releases.md
- lib/jekyll_picture_tag/defaults/presets.yml
- lib/jekyll_picture_tag/output_formats/data_attributes.rb
- lib/jekyll_picture_tag/version.rb
- test/integration/test_presets.rb
- test/stubs/jekyll.rb
- test/unit/output_formats/test_helper_output.rb
Add new feature, as requested. 
@jessecrouch - You'll need to set `data_sizes: false` in the relevant preset, and that should give you a plain `sizes` attribute instead of `data-sizes`. Let me know if it gives you any trouble!
close #155
> Data sizes

- docs/global_configuration.md
- lib/jekyll_picture_tag.rb
- lib/jekyll_picture_tag/defaults/global.yml
- lib/jekyll_picture_tag/instructions/configuration.rb
- lib/jekyll_picture_tag/router.rb
- test/integration/test_config.rb
- test/unit/instructions/test_config.rb
re #161 
These changes add a setting which disables JPT and leaves a placeholder instead, for debugging purposes or to speed up build times when you're not working with images. 
I'm not going to close the issue, because I'd also like to add a 'fast build' option as a middle ground between checking every single image, and returning no images at all. More on that later.
> Off switch

- .rubocop.yml
- jekyll_picture_tag.gemspec
These changes should ensure that new rubocop updates don't break our CI again.
> Rubocop fix

- jekyll_picture_tag.gemspec
> Lock rubocop sub-library minor versions

- docs/users/deployment.md
Add instructions for using Actions to deploy to GitHub Pages.
> Docs: Deploy to GitHub Pages using Actions

- lib/jekyll_picture_tag/parsers/image_backend.rb
A recent vips update has changed some class names, which broke our
format detection. Imagemagick has also slightly changed its `convert
-version` output.
- Filter `vips -l` directly, rather than by passing an argument.
- For Imagemagick, Specifically search for "Delegates" rather than
assuming it will be the last line output.
Close #279
> Fix vips & imagemagick format detection

- lib/jekyll_picture_tag/parsers/image_backend.rb
I added checks to test if `vips` and `convert` are installed before checking for supported file formats. Currently the gem panics if `vips` and/or `convert` are not installed.
> fix: test if vips or convert are installed

- lib/jekyll_picture_tag/images/image_file.rb
Using PPM files were giving errors as vips does not support -Q (quality) parameter.
```
vips VipsForeignSavePpmFile 
save image to ppm file
usage:
ppmsave in filename [--option-name option-value ...]
where:
in           - Image to save, input VipsImage
filename     - Filename to save to, input gchararray
optional arguments:
format       - Format to save in, input VipsForeignPpmFormat
default enum: ppm
allowed enums: pbm, pgm, ppm, pfm, pnm
ascii        - Save as ascii, input gboolean
default: false
bitdepth     - Set to 1 to write as a 1 bit image, input gint
default: 0
min: 0, max: 1
keep         - Which metadata to retain, input VipsForeignKeep
default flags: exif:xmp:iptc:icc:other:all
allowed flags: none, exif, xmp, iptc, icc, other, all
background   - Background value, input …
```
> Fix: Ignore unsupported quality parameter for PPM files

- jekyll_picture_tag.gemspec
I ran into a slight issue when installing another gem, `jekyll-og-image`, due to conflicting `ruby-vips` versions.
```
bundle add jekyll-og-image
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find compatible versions
Because every version of jekyll-og-image depends on ruby-vips ~> 2.2.0
and jekyll_picture_tag >= 2.0.0pre1 depends on ruby-vips ~> 2.0.17,
every version of jekyll-og-image is incompatible with jekyll_picture_tag >= 2.0.0pre1.
So, because Gemfile depends on jekyll_picture_tag ~> 2.1
and Gemfile depends on jekyll-og-image >= 0,
version solving has failed.
```
Since ruby-vips latest version is now 2.2 I believe the most straightforward fix here is to update `jekyll_picture_tag` to use this  version. I'd also be happy to use any …
> Update requirements for ruby-vips

- docs/users/presets/subpresets.md
After seeing the conversation in #271, I decided to quickly go in and document this for people to find easier. I didn't find this syntax very intuitive at first, and it took me a while to wrap my head around it. I wouldn't expect a more casual user to catch on immediately, so I tried to explain it in the most clear way I could, making no assumptions. I also coined the term "subpreset" for this, primarily because it makes it very obvious when skimming the pages list if you're trying to find a feature like this, but also I just thought it sounded cool :p
As a side note, you might wanna update some things to make it easier to contribute to the docs. The theme `rundocs/jekyll-rtd-theme` appears to have disappeared, alongside the entire rundocs account. No idea what happened, but using a …
> Document anchor/alias functionality

- docs/Gemfile
- docs/Gemfile.lock
- docs/_config.yml
- package-lock.json
Whoever was hosting the original RTD theme took down the repo, which is a bit of a jerk move.
Someone else reuploaded it, and I've made my own fork to ensure this doesn't happen again.
> Fix broken documentation
