- lib/jekyll-picture-tag.rb
- readme.md
Been using this for a while here: https://github.com/razor-x/jekyll-and-zurb/blob/master/_plugins/tag-picture.rb. Once I saw this was converted to a gem I figured I would contribute back.
> Add support for ZURB Foundation's Interchange.

- lib/jekyll-picture-tag.rb
#65 
Edit: linked the wrong issue. See delucis' comment below
> pass empty string instead of nil for empty site baseurl

- readme.md
> Correct file path in installation instructions

- lib/jekyll-picture-tag.rb
This makes the output deterministic
> Strip metadata from generated images

- jekyll-picture-tag.gemspec
- lib/jekyll-picture-tag.rb
This only implements srcset, not sizes.
Uses [objective elements](https://github.com/rbuchberger/objective_elements) to build the HTML, because doing it with string concatenation is seriously painful.
> New feature: img tag srcset building

- lib/jekyll-picture-tag/defaults/presets.yml
- lib/jekyll-picture-tag/instructions.rb
- lib/jekyll-picture-tag/instructions/configuration.rb
- lib/jekyll-picture-tag/instructions/html_attributes.rb
- lib/jekyll-picture-tag/instructions/preset.rb
- lib/jekyll-picture-tag/output_formats/basics.rb
- lib/jekyll-picture-tag/utils.rb
- lib/jekyll-picture-tag/version.rb
- readme.md
Add anchor tag wrappers, Documentation improvements
> Anchortags

- lib/jekyll-picture-tag/generated_image.rb
Not sure if there’s a more elegant way to do this, but this ensures images are world readable.
> Sets permissions on images

- lib/jekyll-picture-tag/defaults/global.yml
- lib/jekyll-picture-tag/instructions/configuration.rb
- readme.md
> Adds CDN config option

- lib/jekyll-picture-tag/generated_image.rb
Fixes #125.
You might want to change the filename. Right now it's:
daisy-720-ec0475.png
> Fix inaccurate generated picture size, fixes #125

- docs/notes.md
- docs/releases.md
- jekyll_picture_tag.gemspec
- lib/jekyll_picture_tag/instructions/html_attributes.rb
- lib/jekyll_picture_tag/version.rb
- test/integration/test_presets.rb
fix #153 
Also fix a bug (coming from a dependency) where when the same attribute is given items in both the tag and the preset, only one of them makes it to the final output.
Update docs, bump version.
> Attr bugfix

- docs/presets.md
- jekyll_picture_tag.gemspec
- test/integration/test_presets.rb
- test/stubs/jekyll.rb
- test/unit/instructions/test_html_attributes.rb
- test/unit/output_formats/test_img.rb
Fix #157
The main fix is contained in an update to a dependency which I also maintain. The rest is mostly just adding and updating tests to ensure it works correctly.
> Empty attributes

- lib/jekyll_picture_tag/instructions/configuration.rb
- test/integration/test_params.rb
- test/integration/test_presets.rb
- test/stubs/jekyll.rb
- test/unit/instructions/test_config.rb
> 181 regeneration

- docs/releases.md
- lib/jekyll_picture_tag/output_formats/basic.rb
- lib/jekyll_picture_tag/version.rb
- readme.md
- test/integration/test_presets.rb
> 174 direct url

- docs/users/liquid_tag/examples.md
> Examples to cover gotchas - Liquid Exception: undefined method `include?' for nil:NilClass #193

- docs/users/presets/cropping.md
Should help with #202.
Not totally sure if the media_crop values need to be quoted?
> Update cropping doc

- lib/jekyll_picture_tag.rb
- test/integration/test_params.rb
Gracefully handle empty tag parameters.
close #196
Sorry it took so long!
> 196 - Empty tag parameters

- docs/devs/releases.md
- lib/jekyll_picture_tag/version.rb
- readme.md
Sorry for the changed file noise; I had let some trailing whitespace sneak in to the docs.
> Release 1.14.0

- docs/devs/releases.md
- lib/jekyll_picture_tag/parsers/image_backend.rb
- lib/jekyll_picture_tag/version.rb
- readme.md
Improve image format support detection; handle alternative names for the same format.
> Format detection

- lib/jekyll_picture_tag/parsers/image_backend.rb
- test/unit/parsers/test_backend.rb
When breaking for no known saver, list known savers.
> Improve 'no known savers' error message

- docs/devs/contributing/docs.md
- docs/devs/contributing/setup.md
Edit the setup doc to include the proper repo clone link.
> Edit the setup doc

- docs/users/installation.md
This is a little edit, but it will go a long way to help total beginners.
I'm just doing the necessary fixes as I come across them.
> Edit the installation.md file.

- docs/users/presets/markup_formats/fragments.md
- docs/users/presets/markup_formats/readme.md
Improve documentation as suggested in issue #287.
> [doc] Avoid removed markup_presets in config examples

- docs/users/notes/html_attributes.md
Both of these links are broken. I've added link tags to where (I think) they should be pointing to.
> [doc] Update broken internal links

- .rubocop.yml
- docs/devs/releases.md
- jekyll_picture_tag.gemspec
- lib/jekyll_picture_tag/parsers/image_backend.rb
- lib/jekyll_picture_tag/version.rb
- readme.md
See commits & changelog for details
> Version 2.1.0

- docs/users/notes/html_attributes.md
I have no idea why this only just broke now
> Fix github pages build failure

- docs/index.md
Should have grepped for logo.svg before deleting it
> Fix logo in docs
